/**
 * Design tokens lifted verbatim from the delivered design system:
 *   Design/intellicar_one_ev_platform/.../DESIGN.md frontmatter
 *   Design/intellicar_one_ev_platform/.../code.html (tailwind.config script block)
 *
 * Do not hand-edit values here — if the design system changes, re-sync from DESIGN.md.
 */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-variant': '#dae2fd',
        'surface-tint': '#2151da',
        'on-surface': '#131b2e',
        'on-surface-variant': '#434655',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        outline: '#747686',
        'outline-variant': '#c4c5d7',
        primary: '#0037b0',
        'on-primary': '#ffffff',
        'primary-container': '#1d4ed8',
        'on-primary-container': '#cad3ff',
        'inverse-primary': '#b7c4ff',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#001551',
        'on-primary-fixed-variant': '#0039b5',
        secondary: '#4b41e1',
        'on-secondary': '#ffffff',
        'secondary-container': '#645efb',
        'on-secondary-container': '#fffbff',
        'secondary-fixed': '#e2dfff',
        'secondary-fixed-dim': '#c3c0ff',
        'on-secondary-fixed': '#0f0069',
        'on-secondary-fixed-variant': '#3323cc',
        tertiary: '#004f35',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#006948',
        'on-tertiary-container': '#76eab6',
        'tertiary-fixed': '#85f8c4',
        'tertiary-fixed-dim': '#68dba9',
        'on-tertiary-fixed': '#002114',
        'on-tertiary-fixed-variant': '#005137',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#faf8ff',
        'on-background': '#131b2e',
        // Operational state accents (DESIGN.md "Operational State Accents")
        'state-warn': '#d97706',
        'state-warn-fill': '#fffbeb',
        'state-warn-border': '#fde68a',
        'state-warn-text': '#92400e',
        'state-ok': '#059669',
        'state-ok-fill': '#ecfdf5',
        'state-ok-border': '#a7f3d0',
        'state-ok-text': '#065f46',
        'state-crit': '#e11d48',
        'state-crit-fill': '#fff1f2',
        'state-crit-border': '#fecdd3',
        'state-crit-text': '#9f1239',
        'state-idle': '#64748b',
        'state-idle-fill': '#f1f5f9',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        pill: '9999px',
      },
      spacing: {
        gutter: '1rem',
        'gutter-desktop': '1.5rem',
        margin: '1rem',
        'margin-desktop': '1.5rem',
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
      },
      fontFamily: {
        'headline-xl': ['Inter'],
        'headline-xl-mobile': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'headline-sm': ['Inter'],
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'label-sm': ['Inter'],
        'telemetry-lg': ['JetBrains Mono'],
        'telemetry-md': ['JetBrains Mono'],
        'telemetry-sm': ['JetBrains Mono'],
      },
      fontSize: {
        'headline-xl': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.025em', fontWeight: '700' }],
        'headline-xl-mobile': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['1rem', { lineHeight: '1.5rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.025em', fontWeight: '600' }],
        'label-sm': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.05em', fontWeight: '600' }],
        'telemetry-lg': ['1.5rem', { lineHeight: '1.75rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'telemetry-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'telemetry-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0em', fontWeight: '500' }],
      },
      boxShadow: {
        // DESIGN.md "Elevation & Depth"
        'level-1': '0 1px 2px 0 rgba(15, 23, 42, 0.04)',
        'level-2': '0 4px 6px -1px rgba(15, 23, 42, 0.06), 0 2px 4px -2px rgba(15, 23, 42, 0.04)',
        'level-3': '0 10px 15px -3px rgba(15, 23, 42, 0.08), 0 4px 6px -4px rgba(15, 23, 42, 0.03)',
        'level-4': '0 20px 25px -5px rgba(15, 23, 42, 0.12), 0 8px 10px -6px rgba(15, 23, 42, 0.06)',
      },
    },
  },
  plugins: [],
}
